/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_consolecardgame_GameLogicJavaCallers_Random */

#ifndef _Included_com_example_consolecardgame_GameLogicJavaCallers_Random
#define _Included_com_example_consolecardgame_GameLogicJavaCallers_Random
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_consolecardgame_GameLogicJavaCallers_Random
 * Method:    getRandomCharacter
 * Signature: (Ljava/lang/String;)Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_com_example_consolecardgame_GameLogicJavaCallers_Random_getRandomCharacter
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
